# Generated by Django 5.2.7 on 2025-11-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(help_text='Contact name or organization', max_length=200)),
                ('contact_type', models.CharField(choices=[('police', 'Police'), ('hospital', 'Hospital'), ('fire_brigade', 'Fire Brigade'), ('electricity', 'Electricity Department'), ('water', 'Water Department'), ('sarpanch', 'Sarpanch'), ('talathi', 'Talathi'), ('ambulance', 'Ambulance'), ('disaster', 'Disaster Management'), ('others', 'Others')], help_text='Type of emergency service', max_length=50)),
                ('phone_number', models.CharField(help_text='Contact phone number', max_length=20)),
                ('address', models.TextField(help_text='Complete address')),
                ('email', models.EmailField(blank=True, help_text='Email address (optional)', max_length=254, null=True)),
                ('available_24x7', models.BooleanField(default=False, help_text='Is this service available 24x7?')),
                ('icon', models.CharField(blank=True, help_text='Bootstrap icon class (e.g., bi-telephone-fill)', max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this contact active?')),
            ],
            options={
                'verbose_name': 'Emergency Contact',
                'verbose_name_plural': 'Emergency Contacts',
                'ordering': ['-last_updated'],
            },
        ),
    ]
