# Generated by Django 5.2.7 on 2025-11-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencydirectory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontact',
            name='available_24x7',
            field=models.BooleanField(default=True, help_text='Is this service available 24x7?'),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='icon',
            field=models.CharField(blank=True, default='', help_text='Bootstrap icon class (e.g., bi-telephone-fill)', max_length=50),
        ),
    ]
