# Generated by Django 5.2.7 on 2025-12-31 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencydirectory', '0002_alter_emergencycontact_available_24x7_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencycontact',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address', max_length=100, null=True),
        ),
    ]
