# Generated by Django 5.2.7 on 2026-01-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencydirectory', '0003_alter_emergencycontact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycontact',
            name='closing_time',
            field=models.TimeField(default='18:00', help_text='Closing time for the service'),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='opening_time',
            field=models.TimeField(default='10:00', help_text='Opening time for the service'),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='available_24x7',
            field=models.BooleanField(default=False, help_text='Is this service available 24x7?'),
        ),
    ]
