# Generated by Django 5.2.8 on 2025-11-18 18:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=200)),
                ('asset_type', models.CharField(choices=[('infrastructure', 'Public Infrastructure'), ('property', 'Gram Panchayat Property'), ('vehicle', 'Vehicle'), ('equipment', 'Equipment'), ('furniture', 'Furniture'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('ward_number', models.CharField(blank=True, max_length=50)),
                ('purchase_date', models.DateField()),
                ('purchase_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('damaged', 'Damaged')], default='good', max_length=20)),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
                ('next_maintenance_date', models.DateField(blank=True, null=True)),
                ('responsible_person', models.CharField(blank=True, max_length=200)),
                ('contact_number', models.CharField(blank=True, max_length=15)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='assets/')),
                ('remarks', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=300)),
                ('project_type', models.CharField(choices=[('road', 'Road Construction'), ('water', 'Water Supply'), ('sanitation', 'Sanitation'), ('building', 'Building Construction'), ('electricity', 'Electrification'), ('drainage', 'Drainage System'), ('education', 'Education'), ('health', 'Health'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('ward_number', models.CharField(blank=True, max_length=50)),
                ('budget_allocated', models.DecimalField(decimal_places=2, max_digits=12)),
                ('budget_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('funding_source', models.CharField(choices=[('central', 'Central Government'), ('state', 'State Government'), ('local', 'Local Funds'), ('mplads', 'MPLADS'), ('mgnrega', 'MGNREGA'), ('other', 'Other')], max_length=20)),
                ('start_date', models.DateField()),
                ('target_completion_date', models.DateField()),
                ('actual_completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('approved', 'Approved'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('delayed', 'Delayed'), ('suspended', 'Suspended')], default='proposed', max_length=20)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('contractor_name', models.CharField(blank=True, max_length=200)),
                ('contractor_contact', models.CharField(blank=True, max_length=15)),
                ('beneficiaries_count', models.IntegerField(default=0)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('document', models.FileField(blank=True, null=True, upload_to='project_docs/')),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
