# Generated by Django 5.2.8 on 2025-11-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clerk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='grievance_photos/'),
        ),
    ]
