# Generated by Django 5.1.6 on 2025-11-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clerk', '0002_grievance_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='application_process',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='scheme',
            name='downloadable_forms',
            field=models.FileField(blank=True, null=True, upload_to='scheme_forms/'),
        ),
        migrations.AddField(
            model_name='scheme',
            name='last_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='scheme_image',
            field=models.ImageField(blank=True, null=True, upload_to='scheme_images/'),
        ),
    ]