# Generated by Django 5.2.8 on 2025-12-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clerk', '0003_scheme_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxrecord',
            name='tax_type',
            field=models.CharField(choices=[('property', 'Property Tax'), ('water', 'Water Tax'), ('garbage', 'Garbage Tax'), ('health', 'Health Tax')], max_length=20),
        ),
    ]
