# Generated by Django 5.2.7 on 2025-12-31 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clerk', '0004_alter_taxrecord_tax_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clerkprofile',
            name='designation',
            field=models.CharField(max_length=100),
        ),
    ]
