# Generated by Django 5.1.6 on 2025-11-03 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram_panchayate_system', '0001_initial'),
    ]

    operations = [
    ]
