# Generated by Django 5.2.7 on 2025-11-16 10:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_title', models.CharField(help_text='Title of the meeting', max_length=200)),
                ('meeting_date', models.DateField(help_text='Date of the meeting')),
                ('time', models.TimeField(help_text='Time of the meeting')),
                ('location', models.CharField(help_text='Venue/Location of the meeting', max_length=200)),
                ('agenda', models.TextField(help_text='Meeting agenda and topics')),
                ('organized_by', models.CharField(help_text='Organizer name', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_cancelled', models.BooleanField(default=False, help_text='Is this meeting cancelled?')),
            ],
            options={
                'verbose_name': 'Meeting Schedule',
                'verbose_name_plural': 'Meeting Schedules',
                'ordering': ['meeting_date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='VillageNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Notice title', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the notice')),
                ('notice_type', models.CharField(choices=[('general', 'General'), ('emergency', 'Emergency'), ('announcement', 'Announcement')], default='general', help_text='Type of notice', max_length=20)),
                ('issued_by', models.CharField(help_text='Name of the issuing authority', max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Date of issuance')),
                ('attachment', models.FileField(blank=True, help_text='Optional attachment (PDF, Image, etc.)', null=True, upload_to='notices/attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this notice active?')),
            ],
            options={
                'verbose_name': 'Village Notice',
                'verbose_name_plural': 'Village Notices',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
