# Generated by Django 5.2.7 on 2025-11-17 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbacksuggestion',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Feedback/Suggestion', 'verbose_name_plural': 'Feedback/Suggestions'},
        ),
        migrations.AddField(
            model_name='feedbacksuggestion',
            name='admin_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedbacksuggestion',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='feedback_attachments/'),
        ),
        migrations.AddField(
            model_name='feedbacksuggestion',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedbacksuggestion',
            name='responded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedbacksuggestion',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='feedbacksuggestion',
            name='citizen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feedbacksuggestion',
            name='feedback_type',
            field=models.CharField(choices=[('suggestion', 'Suggestion'), ('complaint', 'Complaint'), ('query', 'Query'), ('appreciation', 'Appreciation')], max_length=20),
        ),
    ]
