# Generated by Django 5.2.7 on 2025-11-17 10:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PanchayatBudget',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Sr. No.')),
                ('budget_head', models.CharField(choices=[('Health Inspection', 'Health Inspection'), ('Electricity Tax', 'Electricity Tax'), ('Garbage Tax', 'Garbage Tax'), ('Public Water Supply', 'Public Water Supply'), ('Other Water Services', 'Other Water Services'), ('Old Product / Previous Income', 'Old Product / Previous Income')], max_length=100)),
                ('previous_year_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('revenue_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('revenue_collection', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('expenditure_allotted', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('expenditure_spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('document', models.FileField(blank=True, null=True, upload_to='budget_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Panchayat Budget',
                'verbose_name_plural': 'Panchayat Budgets',
                'ordering': ['-created_at'],
            },
        ),
    ]
