# Generated by Django 5.2.7 on 2025-12-20 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PanchayatBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(choices=[('2022-2023', '2022-2023'), ('2023-2024', '2023-2024'), ('2024-2025', '2024-2025')], max_length=9, unique=True, verbose_name='Financial Year')),
                ('title', models.CharField(max_length=200, verbose_name='Budget Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('pdf_file', models.FileField(upload_to='budget_pdfs/', verbose_name='PDF File')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Upload Date')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Panchayat Budget',
                'verbose_name_plural': 'Panchayat Budgets',
                'ordering': ['-financial_year'],
            },
        ),
    ]
