# Generated by Django 5.2.7 on 2025-12-31 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panchayat_budget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_head', models.CharField(choices=[('health_inspection', 'Health Inspection'), ('electricity_tax', 'Electricity Tax'), ('garbage_tax', 'Garbage Tax'), ('public_water_supply', 'Public Water Supply'), ('old_product_income', 'Old Product Income'), ('development_works', 'Development Works'), ('education', 'Education'), ('health', 'Health'), ('sanitation', 'Sanitation'), ('water_supply', 'Water Supply'), ('roads', 'Roads'), ('other', 'Other')], max_length=50, verbose_name='Budget Head')),
                ('previous_year_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Previous Year Amount')),
                ('revenue_income', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Revenue Income')),
                ('revenue_collection', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Revenue Collection')),
                ('expenditure_allotted', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Expenditure Allotted')),
                ('expenditure_spent', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Expenditure Spent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'Budget Entry',
                'verbose_name_plural': 'Budget Entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
