# Generated by Django 5.2.7 on 2025-11-16 16:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LandParcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_number', models.CharField(max_length=100)),
                ('gat_number', models.CharField(max_length=100)),
                ('property_id', models.CharField(max_length=100, unique=True)),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=500)),
                ('ownership_type', models.CharField(default='Private', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CertificateApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', models.CharField(choices=[('birth', 'Birth Certificate'), ('death', 'Death Certificate'), ('income', 'Income Certificate'), ('caste', 'Caste Certificate'), ('residence', 'Residence Certificate'), ('marriage', 'Marriage Certificate'), ('farmer', 'Farmer Certificate'), ('senior_citizen', 'Senior Citizen Certificate'), ('bpl', 'BPL Certificate')], max_length=20)),
                ('full_name', models.CharField(max_length=200)),
                ('father_name', models.CharField(max_length=200)),
                ('mother_name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('aadhar', models.CharField(max_length=12)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_clerk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_certificates', to=settings.AUTH_USER_MODEL)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovedCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=50, unique=True)),
                ('certificate_file', models.FileField(upload_to='certificates/approved/')),
                ('approved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approved_certificate', to='certificates_rti.certificateapplication')),
            ],
        ),
        migrations.CreateModel(
            name='CertificateDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='certificates/documents/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='certificates_rti.certificateapplication')),
            ],
        ),
        migrations.CreateModel(
            name='LandRecordLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_number', models.CharField(max_length=100)),
                ('gat_number', models.CharField(max_length=100)),
                ('property_id', models.CharField(max_length=100)),
                ('ownership_proof', models.FileField(upload_to='land_records/proof/')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_records', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_land_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RTIRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('general', 'General'), ('sc', 'Scheduled Caste'), ('st', 'Scheduled Tribe'), ('obc', 'Other Backward Class'), ('bpl', 'Below Poverty Line')], default='general', max_length=20)),
                ('address', models.TextField()),
                ('supporting_doc', models.FileField(blank=True, null=True, upload_to='rti/supporting/')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('responded', 'Responded'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('response_file', models.FileField(blank=True, null=True, upload_to='rti/responses/')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_clerk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_rtis', to=settings.AUTH_USER_MODEL)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rti_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
