# Generated by Django 5.2.8 on 2025-11-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates_rti', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landrecordlink',
            name='ownership_proof',
            field=models.FileField(blank=True, null=True, upload_to='land_records/proof/'),
        ),
        migrations.AlterField(
            model_name='landrecordlink',
            name='property_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
