# Generated by Django 5.2.7 on 2025-12-31 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates_rti', '0002_alter_landrecordlink_ownership_proof_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtirequest',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('sc', 'Scheduled Caste'), ('st', 'Scheduled Tribe'), ('obc', 'Other Backward Class'), ('bpl', 'Below Poverty Line')], max_length=20),
        ),
    ]
