# Generated by Django 5.2.7 on 2025-12-03 14:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenTaxData',
            fields=[
                ('aadhaar_number', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('property_tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('property_due_date', models.DateField(blank=True, null=True)),
                ('property_penalty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('property_status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('overdue', 'Overdue')], default='pending', max_length=10)),
                ('water_tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('water_due_date', models.DateField(blank=True, null=True)),
                ('water_penalty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('water_status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('overdue', 'Overdue')], default='pending', max_length=10)),
                ('garbage_tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('garbage_due_date', models.DateField(blank=True, null=True)),
                ('garbage_penalty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('garbage_status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('overdue', 'Overdue')], default='pending', max_length=10)),
                ('health_tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('health_due_date', models.DateField(blank=True, null=True)),
                ('health_penalty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('health_status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('overdue', 'Overdue')], default='pending', max_length=10)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Citizen Tax Data',
                'verbose_name_plural': 'Citizen Tax Data',
            },
        ),
    ]
